version: '3.1'

services: 
  my_mysql:
    image: mysql
    container_name: my_database
    build: 
      context: .
      dockerfile: Dockerfile_mysql
    volumes: 
      - my_data:/var/lib/mysql
    networks: 
      - red
  web:
    image: my_app
    container_name: my_application
    depends_on:
      - my_database
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '9000:8080'
    networks: 
      - red

networks:
  red:
volumes: 
  my_data: